# Day 5: Data Cleaning
**AI/ML Internship – Task 1**

This notebook cleans `student_data.csv`: handling missing values, removing duplicate rows, fixing inconsistent text labels, and renaming columns. The cleaned file is saved for use in later EDA and modeling tasks.

## 1. Load the raw dataset

In [4]:
import pandas as pd

df = pd.read_csv("../data/student_data.csv")
print("Shape before cleaning:", df.shape)
df.head()

Shape before cleaning: (206, 8)

,Student ID,Name,Gender,Study Hours,Attendance (%),Math Score,Science Score,English Score
0,1195,Asha H.,Male,3.6,95.0,88.0,78.0,99.0
1,1127,Ravi A.,Male,3.3,95.0,82.0,90.0,70.0
2,1023,Rohan R.,Female,3.4,97.0,90.0,78.0,95.0
3,1012,Asha L.,Female,3.8,70.0,91.0,67.0,84.0
4,1157,Asha E.,Male,1.9,63.0,61.0,56.0,65.0

## 2. Handle missing values

First, see exactly how much is missing and where, then decide how to handle it.
For numeric score/attendance columns, filling with the **column median** is safer than the mean,
since it's less affected by outliers.

In [5]:
df.isnull().sum()

Student ID        0
Name              0
Gender            0
Study Hours       5
Attendance (%)    6
Math Score        9
Science Score     6
English Score     8
dtype: int64

In [6]:
numeric_cols = ["Study Hours", "Attendance (%)", "Math Score", "Science Score", "English Score"]

for col in numeric_cols:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)
    print(f"Filled missing values in '{col}' with median = {median_value}")

Filled missing values in 'Study Hours' with median = 3.9
Filled missing values in 'Attendance (%)' with median = 79.0
Filled missing values in 'Math Score' with median = 83.0
Filled missing values in 'Science Score' with median = 80.0
Filled missing values in 'English Score' with median = 84.0

In [7]:
# Confirm no missing values remain
df.isnull().sum()

Student ID        0
Name              0
Gender            0
Study Hours       0
Attendance (%)    0
Math Score        0
Science Score     0
English Score     0
dtype: int64

## 3. Remove duplicate rows

In [8]:
print("Duplicate rows found:", df.duplicated().sum())

Duplicate rows found: 6

In [9]:
df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (200, 8)

## 4. Fix inconsistent text values

The `Gender` column has inconsistent labels like `male`, `Male`, `female `, `Female` (with stray
capitalization and whitespace). Standardize these before any grouping or analysis.

In [10]:
df["Gender"].unique()

<StringArray>
['Male', 'Female', 'female ', 'male']
Length: 4, dtype: str

In [11]:
df["Gender"] = df["Gender"].str.strip().str.capitalize()
df["Gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

## 5. Rename columns for consistency
Use lowercase, underscore-separated names, which are easier to work with in code.

In [12]:
df = df.rename(columns={
    "Student ID": "student_id",
    "Name": "name",
    "Gender": "gender",
    "Study Hours": "study_hours",
    "Attendance (%)": "attendance_pct",
    "Math Score": "math_score",
    "Science Score": "science_score",
    "English Score": "english_score",
})
df.columns.tolist()

['student_id',
 'name',
 'gender',
 'study_hours',
 'attendance_pct',
 'math_score',
 'science_score',
 'english_score']

## 6. Final check

In [13]:
print("Final shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nGender values:", df["gender"].unique())
df.head()

Final shape: (200, 8)

Missing values:
 student_id        0
name              0
gender            0
study_hours       0
attendance_pct    0
math_score        0
science_score     0
english_score     0
dtype: int64

Duplicate rows: 0

Gender values: <StringArray>
['Male', 'Female']
Length: 2, dtype: str

,student_id,name,gender,study_hours,attendance_pct,math_score,science_score,english_score
0,1195,Asha H.,Male,3.6,95.0,88.0,78.0,99.0
1,1127,Ravi A.,Male,3.3,95.0,82.0,90.0,70.0
2,1023,Rohan R.,Female,3.4,97.0,90.0,78.0,95.0
3,1012,Asha L.,Female,3.8,70.0,91.0,67.0,84.0
4,1157,Asha E.,Male,1.9,63.0,61.0,56.0,65.0

## 7. Save the cleaned dataset

In [14]:
df.to_csv("../data/student_data_cleaned.csv", index=False)
print("Saved cleaned dataset to ../data/student_data_cleaned.csv")

Saved cleaned dataset to ../data/student_data_cleaned.csv

## 8. Practice Exercises
1. Instead of filling missing `Math Score` with the median, try filling it with the mean, and compare the two values.
2. Count how many rows had at least one missing value before cleaning (hint: use the raw dataframe before `fillna`).
3. Check if any `student_id` values are duplicated even if the full row isn't (use `df["student_id"].duplicated().sum()`).
4. Create a new column `average_score` that is the mean of `math_score`, `science_score`, and `english_score`.
5. Save a second version of the cleaned file as an Excel file instead of CSV (hint: `df.to_excel(...)`, needs `openpyxl` installed).

In [ ]:
# Exercise 1

In [ ]:
# Exercise 2

In [ ]:
# Exercise 3

In [ ]:
# Exercise 4

In [ ]:
# Exercise 5

## 9. Observations

- Missing values in numeric columns were filled with the column median to avoid distortion from outliers.
- Duplicate rows were removed, reducing the dataset from its original size.
- The `gender` column had inconsistent capitalization and stray whitespace, now standardized to `Male` / `Female`.
- Column names were converted to a consistent lowercase, underscore style for easier use in code.
- The cleaned dataset is saved separately as `student_data_cleaned.csv`, keeping the original raw file untouched for reference.